name: xboard-server
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: xboard
      POSTGRES_PASSWORD: xboard
      POSTGRES_DB: xboard
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres:
